name = "Mod Name"
prefix = "TAG"
author = "Your Name"
template = "cba"
mainprefix = "z"
folder_optionals = true
sig_version = 3
files = [
    "mod.cpp",
    "*.paa"
]

[version]
git_hash = 0 # Disabled
